## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/transport?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

## Mybatis 配置
mybatis:
  typeAliasesPackage: com.transprot.user.dao
  mapperLocations: classpath:mapper/*.xml